name: flutternetworking
description: Flutter networking example - http.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.0
  json_annotation: ^3.0.1
  cupertino_icons: ^0.1.3
  toast: ^0.1.5
  logger: ^0.9.1
  retrofit: ^1.3.4
  dio: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  retrofit_generator: ^1.3.7

flutter:
  uses-material-design: true
